DROP TABLE IF EXISTS vegetables;
DROP TABLE IF EXISTS fruits;
DROP TABLE IF EXISTS nuts;

CREATE TABLE vegetables (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT,
  size TEXT
);

CREATE TABLE fruits (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT,
  size TEXT
);

CREATE TABLE nuts (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  size TEXT CHECK ( size = ANY('{small, medium, large}')),
  is_good BOOLEAN
);